name: tests

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      - name: Set up Python
        uses: actions/setup-python@v5
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .
      - name: Run tests
        run: pytest tests/ --durations=0
